site_name: QED Test Automation Framework 
site_url: https://anevisser.github.io/qed-framework/
repo_url: https://github.com/AneVisser/qed-framework
repo_name: QED
docs_dir: docs
site_dir: site
use_directory_urls: false

theme:
  name: material
  logo: ./images/QED_Logo_Only.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top      
    - navigation.prune    
    - toc.follow          
    - toc.integrate       
    - content.code.annotate
    - content.math
  palette:
    scheme: default
    primary: lightblue
    accent: lime
    

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list                  # useful if you want fenced-attrs like ```kotlin {..}
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      line_spans: __span
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js
  - assets/extra.js
extra_css:
  - assets/custom.css
  - assets/extra.css
nav: 
  - Home: index.md 
  - Getting Started: 
      - Prerequisites: getting-started/prerequisites.md 
      - Installation: getting-started/installation.md
      - Custom Test Suites: getting-started/customtestsuites.md
  - DSL:
      - Overview: dsl/overview.md
      - Core constructs: dsl/core-constructs.md
      - Idiomatic patterns: dsl/idiomatic-patterns.md
      - JSON utilities: dsl/jsonutils.md
  - Configuring SUT's: sut/sut-profiles.md
  - Page Objects: page-objects/screen-area-composition.md
  - REST & TDD:
      - Setup: rest/setup.md
      - DSL for APIs: rest/dsl-for-apis.md
      - TDD Workflow: rest/tdd-workflow.md
      - Performance testing: rest/performance.md
      - Sharing with Ktor: rest/ktor_sharing.md
      - testing EMails with Mailpit: rest/testing-emails.md
      - setting up Mailpit: rest/setup-mailpit.md
  - CI/CD:
      - CI/CD Overview & Runner Setup: ci-cd/runner-setup.md
      - Wiring Tests into a Deploy Pipeline: ci-cd/wiring-tests.md
  - Philosophy:
      - Origin Story: philosophy/origin-story.md
      - Design Principles: philosophy/design-principles.md
      - Behaviour driven style: philosophy/bdd.md
  - Reporting:
      - ExtentReports Setup: reporting/extent-reports.md
#      - Test Tags & Filtering: reporting/test-tags.md
#  - AI:
#      - Overview: ai/overview.md
#      - Ollama: ai/ollama.md
#      - Architecture: ai/architecture.md
#  - Tutorials:
#      - Step-by-Step Guides: tutorials/step-by-step.md
#      - Real-World Scenarios: tutorials/real-world-scenarios.md
#      - Common Pitfalls: tutorials/common-pitfalls.md
  - Community:
      - How to Contribute: community/how-to-contribute.md
      - Roadmap: community/roadmap.md
      - Acknowledgments: community/acknowledgements.md